version: '3.8'

services:
  frontend-test:
    build:
      context: .
      dockerfile: Dockerfile
      target: test
      args:
        BUILD_ENV: test
    ports:
      - "9080:80"
    environment:
      - BUILD_ENV=test
      - STANDALONE_MODE=true
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 5s
      timeout: 2s
      retries: 2
      start_period: 5s

networks:
  default:
    name: finviz-network-test
