version: '3.8'

services:
  backend:
    build:
      context: ./finviz_scanner
      dockerfile: docker/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - ALPACA_API_KEY=${ALPACA_API_KEY}
      - ALPACA_SECRET_KEY=${ALPACA_SECRET_KEY}
      - ALPACA_BASE_URL=${ALPACA_BASE_URL}
    volumes:
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - finviz_network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend.prod
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
    volumes:
      - ./nginx.conf.template:/etc/nginx/nginx.conf.template:ro
      - ./frontend.html:/usr/share/nginx/html/index.html:ro
      # Mount Let's Encrypt certificates from local certbot directory
      - ./certbot/conf:/etc/letsencrypt:ro
      - ./certbot/www:/var/www/certbot:ro
    environment:
      - DOMAIN_NAME=amir-trader.duckdns.org
      - BACKEND_URL=http://backend:8000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - finviz_network

  # Optional: Certbot for certificate renewal
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    # Run certbot renewal check once per day
    command: sh -c "while :; do sleep 12h & wait; certbot renew --quiet; done"
    networks:
      - finviz_network

networks:
  finviz_network:
    name: finviz_scanner_network
